baseURL: "https://thefron.me/"
languageCode: "ko-kr"
title: "Thefron"
theme: "fron"
pygmentsCodeFences: true
disqusShortname: thefron
googleAnalytics: "UA-22237907-1"

author:
  name: Hoseong Hwang

menu:
  main:
    - identifier: "about"
      name: "About"
      title: "blog section"
      url: "/about/"
      weight: -110

    - identifier: "blog"
      name: "Posts"
      title: "blog section"
      url: "/posts/"
      weight: -110

params:
  homeSubtitle: 개발로그 + 잡다한 것들

  social:
    - name: github
      url: https://github.com/thefron
    - name: twitter
      url: https://twitter.com/thefron
